[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "openapi_doc_generator"
version = "0.0.17"
requires-python = ">=3.8"
dependencies = [
    "jinja2>=3.1",
    "graphql-core>=3.2",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "ruff",
    "bandit",
]

[tool.setuptools]
package-dir = {"" = "src"}
packages = [
    "openapi_doc_generator",
    "openapi_doc_generator.templates",
]

[project.scripts]
"openapi-doc-generator" = "openapi_doc_generator.cli:main"

[tool.setuptools.package-data]
"openapi_doc_generator.templates" = ["*.jinja"]
