name: CI

on:
  push:
  pull_request:

env:
  PIP_DISABLE_PIP_VERSION_CHECK: '1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-${{ hashFiles('**/pyproject.toml') }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install ruff bandit pytest coverage radon
      - name: Run ruff checks
        run: |
          ruff format --check .
          ruff check .
      - name: Run bandit
        run: bandit -r src
      - name: Run tests with coverage
        run: |
          coverage run -m pytest -q
          coverage xml
      - name: Upload coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage.xml
      - name: Check complexity
        run: |
          radon cc src -n C -s > radon.txt
          if [ -s radon.txt ]; then
            cat radon.txt
            exit 1
          fi
