name: Docs

on:
  push:
    branches: [main]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install package
        run: |
          python -m pip install --upgrade pip
          pip install -e .
      - name: Generate docs
        run: |
          mkdir -p docs
          openapi-doc-generator --app examples/app.py --format markdown --output docs/API.md
          openapi-doc-generator --app examples/app.py --format openapi --output docs/openapi.json
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
